[package]
name = "monkey"
version = "0.1.0"
authors = ["wangbyby <42870190+wangbyby@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand="0.5"
lazy_static = "1.4.0"
thiserror = "1.0"